---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graph-config
data:
  NEO4J_URI: "bolt://neo4j:7687"
  NEO4J_USER: "neo4j"
  NEO4J_PASSWORD: "mySecretPassword"
  GRAPHQL_LISTEN_PORT: "4001"
  GRAPHQL_SERVER_HOST: "0.0.0.0"
  GRAPHQL_SERVER_PATH: "/graphql"